name: ditonton
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  firebase_core: ^3.8.1
  firebase_crashlytics: ^4.2.0
  cupertino_icons: ^1.0.2
  get_it: ^7.1.3
  about:
    path: about
  core:
    path: core
  search:
    path: search

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/
    - certificates/
