name: search
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core

  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  build_runner: ^2.0.4
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7

flutter:
