name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  google_fonts: ^6.2.1
  dartz: ^0.10.0-nullsafety.2
  sqflite: ^2.0.0+3
  cached_network_image: ^3.0.0
  provider: ^6.0.3
  flutter_rating_bar: ^4.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  build_runner: ^2.0.4
  flutter_lints: ^4.0.0

flutter:

